### ISSUE TITLE
Typo 🐺🤘

### ISSUE THREAD

**Issue by agahkarakuzu** [rrsg2020/paper#1]
Ecem Bozhurt --> Ecem Bozkurt

**Comment by mathieuboudreau** [comment]
Fix in [b786998](https://github.com/rrsg2020/paper/commit/b786998d8b0a8b0572153dc261e8a158e86903d5) - thanks! Co-author might have made a typo in my Google Sheet - that's how it was written there. Fixed also in the Google Doc!
